20 test accessibility and ol
gcxchange-gcechange/react-gcx-footer pull request #21
Opened 2023-08-23 16:47 UTC by RVany

All the modification made in this branch is updated in [corresponding DevOps Issue](https://dev.azure.com/tbs-sct/GCExchange/_workitems/edit/10345/)

2023-08-24 13:57 UTC, Steph4104 requested changes

2023-08-24 13:57 UTC, Steph4104 commented on src/webparts/footerWebpart/components/FooterWebpart.tsx
> +                  </div>
Remove all the comment out code

2023-08-24 16:08 UTC, RVany commented on src/webparts/footerWebpart/components/FooterWebpart.tsx
> +                  </div>
Comments deleted.

2023-08-28 17:58 UTC, Steph4104 approved these changes

2023-08-28 20:32 UTC, merged